# Generated by Django 5.2.7 on 2025-10-29 03:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_id",
                    models.CharField(help_text="Session identifier", max_length=100),
                ),
                ("query", models.TextField(help_text="User's query")),
                ("response", models.TextField(help_text="AI-generated response")),
                (
                    "tool_used",
                    models.CharField(
                        blank=True,
                        help_text="Which tool was used (CareerGraph or CourseRecommendations)",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "response_time",
                    models.FloatField(
                        blank=True, help_text="Response time in seconds", null=True
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who made the query (null for anonymous)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Chat History",
                "verbose_name_plural": "Chat Histories",
                "ordering": ["-timestamp"],
            },
        ),
    ]
